# the headless service is for PetSet DNS, this one is for clients
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  externalIPs:
  - 128.195.52.61
  ports:
  - port: 2181
    name: client
    targetPort: 2181
  selector:
    app: zk
